#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : columbiad
Version  : 60bb06a68257557a6f2333fd9310f7f42e434ed3
Release  : 4
URL      : https://github.com/sofar/columbiad/archive/60bb06a68257557a6f2333fd9310f7f42e434ed3.tar.gz
Source0  : https://github.com/sofar/columbiad/archive/60bb06a68257557a6f2333fd9310f7f42e434ed3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: columbiad-bin = %{version}-%{release}
Requires: columbiad-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(gtk+-3.0)

%description
columbiad
---------
> "A frightful silence hung over all that scene. There was not a breath of
> wind on the earth! Not a sound of breathing from the crowd! Hearts dared
> not beat. Every eye was fixed on the gaping mouth of the Columbiad."

%package bin
Summary: bin components for the columbiad package.
Group: Binaries
Requires: columbiad-license = %{version}-%{release}

%description bin
bin components for the columbiad package.


%package license
Summary: license components for the columbiad package.
Group: Default

%description license
license components for the columbiad package.


%prep
%setup -q -n columbiad-60bb06a68257557a6f2333fd9310f7f42e434ed3
cd %{_builddir}/columbiad-60bb06a68257557a6f2333fd9310f7f42e434ed3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604538705
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/columbiad
cp %{_builddir}/columbiad-60bb06a68257557a6f2333fd9310f7f42e434ed3/LICENSE %{buildroot}/usr/share/package-licenses/columbiad/f0aaeb9183bca4511d21c13a39052e24f3774645
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/columbiad

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/columbiad/f0aaeb9183bca4511d21c13a39052e24f3774645
